### ISSUE TITLE
Would be nice to have String() method on BibEntry too

### ISSUE THREAD

**Issue by rcoreilly** [nickng/bibtex#10]
I'm looking up individual entries and showing those to the user, so being able to print those out in a nice format would be great too.  You could just have the BibTex version call the BibEntry one so it is the same code, just packaged differently.

Also, `strings.Builder` might be more efficient than using `bytes.Buffer` for these methods.

**Comment by nickng** [comment]
Thanks for the suggestions!

> `strings.Builder` might be more efficient than using `bytes.Buffer`

I've looked into it but that's not quite what we'd expected (under go1.14)

Benchmark results for `bytes.Buffer` (existing)
```
$ cat /tmp/bytes_buffer.txt
goos: linux
goarch: amd64
pkg: github.com/nickng/bibtex
BenchmarkStringPerformance-12    	    2890	    417485 ns/op
PASS
ok  	github.com/nickng/bibtex	1.264s
```
Benchmark results for `strings.Builder` (replacing `bytes.Buffer` if applicable)
```
$ cat /tmp/strings_builder.txt
goos: linux
goarch: amd64
pkg: github.com/nickng/bibtex
BenchmarkStringPerformance-12    	    2646	    424202 ns/op
PASS
ok  	github.com/nickng/bibtex	1.184s
```

So the overall result looks like this:
```
$ benchcmp /tmp/bytes_buffer.txt /tmp/strings_builder.txt
benchmark                         old ns/op     new ns/op     delta
BenchmarkStringPerformance-12     415490        424202        +2.10%
```

I think I'll hold off this optimisation until the library's performance is improved.
