### ISSUE TITLE
go get produces "too many errors"

### ISSUE THREAD

**Issue by keremgocen** [nickng/bibtex#2]
go version go1.6.2 darwin/amd64

> $ go get -u github.com/nickng/bibtex
> github.com/nickng/bibtex
> ../../../nickng/bibtex/lexer.go:21: undefined: bibtexSymType
> ../../../nickng/bibtex/scanner.go:64: undefined: ATSIGN
> ../../../nickng/bibtex/scanner.go:66: undefined: COLON
> ../../../nickng/bibtex/scanner.go:68: undefined: COMMA
> ../../../nickng/bibtex/scanner.go:70: undefined: EQUAL
> ../../../nickng/bibtex/scanner.go:77: undefined: LBRACE
> ../../../nickng/bibtex/scanner.go:82: undefined: RBRACE
> ../../../nickng/bibtex/scanner.go:119: undefined: IDENT
> ../../../nickng/bibtex/scanner.go:139: undefined: IDENT
> ../../../nickng/bibtex/scanner.go:163: undefined: IDENT
> ../../../nickng/bibtex/scanner.go:163: too many errors

**Comment by nickng** [comment]
Workround: `go generate` should fix this.
