### ISSUE TITLE
Global `bibs` doesn't allow multiple databases

### ISSUE THREAD

**Issue by hildensia** [nickng/bibtex#4]
Hi, I'm trying to use your parser for a hugo (https://www.github.com/spf13/hugo) extension to parse bibtex files to put publications on a webpage.

However, when I want multiple publications databases, I'd need to reset the `bibs` global variable in your package. (https://github.com/nickng/bibtex/blob/master/bibtex.y.go#L16) Is there a chance to get it non-global?

**Comment by nickng** [comment]
Sure, I think that's doable. I'll try to push a fox later today.

**Comment by nickng** [comment]
There is still a global `bib` to store current bibtex while parsing, but if you use the `Parse` function to obtain the pased bibtex, you'll get a new instance of bibtex.

Technically it's possible to completely get rid of `bib` but everything will have to be bubbled up to the toplevel which I try to avoid. In any case `bib` is not part of the exported API so it should not matter.
